// battle-towers-next/src/components/features/battleJournal/BattleJournal.tsx
import styles from './../../../assets/scss/modules/BattleJournal.module.scss';
import enemies from './../../../assets/img/journal/contents/enemies.png';
import towers from './../../../assets/img/journal/contents/towers.png';
import rules from './../../../assets/img/journal/contents/rules.png';
import { useEffect, useState } from 'react';
import Rules from './Rules';
import Enemies from './Enemies';
import Towers from './Towers';
import { animated, useSpring } from 'react-spring';

// import hoverElement from './../../../assets/audio/effects/towerPlace.wav';
// import confirmElement from './../../../assets/audio/effects/confirmMenu.wav';
import useSound from 'use-sound';
import { BattleJournalPage } from '../../../../enums';
import Image from 'next/image';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTimes } from '@fortawesome/free-solid-svg-icons';

interface BattleJournalProps {
    isHelpOpen: boolean,
    setIsHelpOpen: (isOpen: boolean) => void;
}

const BattleJournal: React.FC<BattleJournalProps> = ({ isHelpOpen, setIsHelpOpen }) => {

    // const [playConfirm] = useSound(confirmElement)
    // const [playHover] = useSound(hoverElement);

    const stateAppearAnimation = useSpring({
        from: {
            opacity: isHelpOpen ? 0 : 1,
            translateY: isHelpOpen ? `-100vh` : `0`,
        },
        to: {
            opacity: isHelpOpen ? 1 : 0,
            translateY: isHelpOpen ? `0` : `-100vh`,
        },
        config: { duration: 200 }
    });

    const [activeArticle, setActiveArticle] = useState(BattleJournalPage.RULES);

    const handleActive = (e: React.MouseEvent, page: BattleJournalPage) => {
        const articles = document.querySelectorAll('article');
        articles.forEach((article) => {
            article.classList.remove(styles.active);
        });
        const target = e.target as HTMLDivElement;
        target.closest('article')?.classList.add(styles.active);
        setActiveArticle(page);
        // playConfirm();
    }

    const handleClose = () => {
        setIsHelpOpen(!isHelpOpen);
        // playConfirm();
    }

    const handlePlayHover = (e: React.MouseEvent) => {
        const article = e.target as HTMLDivElement;
        if (!article.classList.contains(styles.active)) {
            // playHover();
        }
    }

    useEffect(() => {
        const modal = document.querySelector(styles.battleJournal);
        if (modal) modal.classList.add(styles.active);
    }, []);

    return (
        <animated.section className={`${styles.battleJournal} ${isHelpOpen && styles.active}`} style={stateAppearAnimation}>
            <div className={styles.modal}>
                <h3 className={styles.header}>Battle Journal</h3>
                <div className={styles.articles}>
                    <article className={styles.active} onMouseEnter={(e) => handlePlayHover(e)} onClick={e => handleActive(e, BattleJournalPage.RULES)}>
                        <Image src={rules} alt="Rules icon" />
                        <h3>Rules</h3>
                    </article>
                    <article onMouseEnter={(e) => handlePlayHover(e)} onClick={e => handleActive(e, BattleJournalPage.ENEMIES)}>
                        <Image src={enemies} alt="Enemies icon" />
                        <h3>Enemies</h3>
                    </article>
                    <article onMouseEnter={(e) => handlePlayHover(e)} onClick={e => handleActive(e, BattleJournalPage.TOWERS)}>
                        <Image src={towers} alt="Towers icon" />
                        <h3>Towers</h3>
                    </article>
                </div>
                <div className={styles.content}>
                    {activeArticle === BattleJournalPage.RULES && <Rules />}
                    {activeArticle === BattleJournalPage.ENEMIES && <Enemies />}
                    {activeArticle === BattleJournalPage.TOWERS && <Towers />}
                </div>
                {/* <i className={`${styles.close} fa fa-times`} onMouseEnter={() => playHover()} onClick={handleClose} /> */}
                <div onClick={handleClose} className={styles.close}>
                    <FontAwesomeIcon
                        icon={faTimes}
                        aria-hidden={true}
                    />
                </div>
            </div>
        </animated.section>
    );
};

export default BattleJournal;

// battle-towers-nuxt/components/features/battleJournal/BattleJournal.vue
<template>
    <section :class="[appStore.isHelpOpen ? 'battleJournal active' : 'battleJournal']">
        <div class="modal">
            <h3 class="header">Battle Journal</h3>
            <div class="articles">
                <article @mouseenter="playHoverEffect" :class="[activeArticle === BattleJournalPage.RULES ? 'active' : '']"
                    @click="handleActive(BattleJournalPage.RULES)">
                    <img :src="rules" alt="Rules icon" />
                    <h3>Rules</h3>
                </article>
                <article @mouseenter="playHoverEffect"
                    :class="[activeArticle === BattleJournalPage.ENEMIES ? 'active' : '']"
                    @click="handleActive(BattleJournalPage.ENEMIES)">
                    <img :src="enemies" alt="Enemies icon" />
                    <h3>Enemies</h3>
                </article>
                <article @mouseenter="playHoverEffect" :class="[activeArticle === BattleJournalPage.TOWERS ? 'active' : '']"
                    @click="handleActive(BattleJournalPage.TOWERS)">
                    <img :src="towers" alt="Towers icon" />
                    <h3>Towers</h3>
                </article>
            </div>
            <div class="content">
                <Rules v-if="activeArticle === BattleJournalPage.RULES" />
                <Enemies v-if="activeArticle === BattleJournalPage.ENEMIES" />
                <Towers v-if="activeArticle === BattleJournalPage.TOWERS" />
            </div>
            <i class="close fa fa-times" @mouseenter="playHoverEffect" @click="handleClose" />
        </div>
    </section>
</template>
  
<script lang="ts">
import { ref, onMounted } from 'vue';
import enemies from './../../../assets/img/journal/contents/enemies.png';
import towers from './../../../assets/img/journal/contents/towers.png';
import rules from './../../../assets/img/journal/contents/rules.png';
import { BattleJournalPage } from '@/typescript/enums';
import Rules from './Rules.vue';
import Enemies from './Enemies.vue';
import Towers from './Towers.vue';
import { useAppStore } from '@/stores/app';
import playConfirm from '@/assets/audio/effects/confirmMenu.wav';
import playHover from '@/assets/audio/effects/towerPlace.wav';

export default {
    name: 'BattleJournal',
    components: {
        Rules,
        Enemies,
        Towers
    },
    setup() {
        const appStore = useAppStore();
        const activeArticle = ref(BattleJournalPage.RULES);
        const handleActive = (page: BattleJournalPage) => {
            const articles = document.querySelectorAll('article');
            articles.forEach((article) => {
                article.classList.remove('active');
            });
            if (!event) return;
            else {
                const target = event.target;
                if (!target) return;
                target.closest('article')?.classList.add('active');
                activeArticle.value = page;
            }
            const audio = new Audio(playConfirm);
            audio.play();
        };
        const handleClose = () => {
            appStore.setIsHelpOpen(false)
            const audio = new Audio(playConfirm);
            audio.play();
        }
        const playHoverEffect = () => {
            const audio = new Audio(playHover);
            audio.play();
        }
        onMounted(() => {
            const modal = document.querySelector('battleJournal');
            if (modal) modal.classList.add('active');
        });

        return {
            appStore,
            BattleJournalPage,
            activeArticle,
            rules,
            enemies,
            towers,
            handleActive,
            handleClose,
            playHoverEffect,
        };
    }
};
</script>
  
<style scoped lang="scss">
@import './../../../assets/scss/variables';

.battleJournal {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    width: 100vw;
    height: 100vh;
    transition-duration: .4s;
    // opacity: 1;
    background-color: rgba($color: #000000, $alpha: .9);
    display: flex;
    justify-content: center;
    align-items: center;

    &.active {
        transition-duration: .4s;
        opacity: 1;
    }

    .modal {
        position: relative;
        background-color: $bgColor;
        height: 80%;
        width: 60%;
        border-radius: 4px;
        border: 2px solid $secondaryColor;
        box-shadow: 0 0 2px 2px $secondaryColor;

        .close {
            position: absolute;
            right: -3rem;
            top: -4rem;
            font-size: 6rem;
            color: $primaryColor;
            transition-duration: .4s;

            &:hover {
                transform: rotate(180deg);
                cursor: pointer;
                color: $secondaryColor;
            }
        }

        .header {
            font-size: 6rem;
            text-align: center;
            font-family: $titleFont;
            padding: 2rem;
            background-image: linear-gradient(180deg, $primaryColor 0%, $bgColor 100%);
            background-clip: text;
            -webkit-background-clip: text;
            color: transparent;
            -webkit-text-stroke: 2px $bgColor;
            filter: drop-shadow(0 0 5px $secondaryColor);
            border-bottom: 2px solid $secondaryColor;
        }

        .overlay {
            background-color: $bgColor;
            width: 100%;
            z-index: 10;
        }

        .articles {
            position: absolute;
            top: 20%;
            display: flex;
            margin-left: -8%;
            flex-direction: column;
            color: $bgColor;
            z-index: -10;

            article {
                display: flex;
                align-items: center;
                width: 25vmin;
                height: 8vmin;
                text-align: center;
                border: 2px solid $primaryColor;
                padding: 10px;
                border-radius: 4px;
                margin: 5% 0;
                background-color: $primaryColor;
                transition-duration: .4s;

                &.active {
                    transform: translateX(-50%);
                    background-color: $secondaryColor;
                    color: $fontColor;
                    transform: translateX(-50%);

                    & img {
                        filter: invert(98%) sepia(0%) saturate(7405%) hue-rotate(195deg) brightness(120%) contrast(58%);
                    }
                }

                h3 {
                    margin-left: 10%;
                }

                img {
                    width: 30%;
                    height: 80%;
                    filter: invert(4%) sepia(2%) saturate(3316%) hue-rotate(201deg) brightness(99%) contrast(80%);
                }

                &:hover {
                    cursor: pointer;
                    background-color: $secondaryColor;
                    color: $fontColor;
                    transform: translateX(-50%);

                    & img {
                        filter: invert(98%) sepia(0%) saturate(7405%) hue-rotate(195deg) brightness(120%) contrast(58%);
                    }
                }
            }
        }

        .content {
            max-height: 65vh;
            overflow-y: auto;

            h2 {
                text-align: center;
                margin: 1rem;
                color: $fontColor;
                font-size: 5rem;
                font-family: $primaryFont;
            }

            .rulesHeader {
                text-align: center;
                margin: 1rem;
                color: $primaryColor;
                font-size: 4rem;
                font-family: $supportFont;
                margin: 3rem 0;
            }

            .rulesParagraph {
                font-size: 2rem;
                line-height: 200%;
                color: $fontColor;
                text-align: justify;
                padding: 0 6rem;
                font-family: $primaryFont;
                text-align: center;

                span {
                    display: block;
                    text-align: center;
                }

                img {
                    margin-top: 10px;
                    width: 20%;
                    height: 20%;
                }

                strong {
                    color: $primaryColor;
                }

                .health {
                    color: $errorColor;
                }

                .money {
                    color: $successColor;
                }
            }

            .goodLuck {
                color: rebeccapurple;
            }

            .enemies {
                margin-top: 3rem;
            }

            .cards {
                display: flex;
                justify-content: space-evenly;
                align-items: center;

                .card {
                    display: flex;
                    flex-direction: column;
                    justify-content: center;
                    align-items: center;
                    border: 2px solid $primaryColor;
                    width: 30%;
                    padding: 20px;
                    color: $fontColor;
                    line-height: 250%;
                    font-size: 1.5rem;
                    border-radius: 4px;
                    background-color: darken($bgColor, 4%);

                    .imgWrapper {
                        height: 15vh;
                        margin: 1rem;

                        img {
                            width: 100%;
                            height: 100%;
                        }
                    }

                    .health {
                        color: $errorColor;
                    }

                    .money {
                        color: $successColor;
                    }

                    .score {
                        color: $primaryColor;
                    }

                    .speed {
                        color: gold;
                    }

                    .opponent {
                        span {
                            display: block;
                        }

                        color: rebeccapurple;
                        text-align: center;
                    }
                }
            }
        }
    }
}
</style>
