// battle-towers-vue/src/BattleTowers.vue
<template>
    <div class="wrapper">
        <div class="game">
            <template v-if="!isGameStart">
                <header class="logo">
                    <div class="imageWrapper">
                        <img src="@/assets/img/shield.png" alt="Shield - element of Battle Towers logo" />
                    </div>
                    <h1>Battle Towers</h1>
                </header>
                <template v-if="!changeState">
                    <Intro :setChangeState="setChangeState" />
                </template>
                <template v-else>
                    <Menu />
                </template>
            </template>
            <template v-else>
                <template v-if="endGame === GameResult.UNPLAYED">
                    <Game />
                </template>
            </template>
            <template v-if="endGame !== GameResult.UNPLAYED">
                <End :gameResult="endGame" />
            </template>
        </div>
    </div>
</template>
  
<script lang="ts">
//   import { ref, computed, useContext } from 'vue';
import { ref, computed } from 'vue';
//   import { AppContext, AppContextType } from './AppContext';
import Intro from './components/views/Intro.vue';
import Menu from './components/views/Menu.vue';
import Game from './components/views/Game.vue';
import End from './components/views/End.vue';
import { GameResult } from './../enums';

export default {
    components: {
        Intro,
        Menu,
        Game,
        End,
    },
    setup() {
        const changeState = ref(false);
        //   const { isGameStart, endGame, playMenu } = useContext(AppContext) as AppContextType;
        const isGameStart = false;
        const endGame = GameResult.UNPLAYED;
        const setChangeState = (accept: boolean) => {
            changeState.value = accept;
        };

        return {
            changeState,
            isGameStart,
            endGame,
            setChangeState,
            GameResult,
        };
    },
};
</script>
  
<style lang="scss" scoped>
@import './assets/scss/variables';

.logo {
    position: relative;
    animation: moveHeader 2s ease-out forwards;
    transform: scale(1.4);

    h1 {
        position: absolute;
        font-family: $titleFont;
        font-size: 12rem;
        width: 300%;
        text-align: center;
        top: 30%;
        left: -100%;
        right: 0;
        background-image: linear-gradient(180deg, $primaryColor 0%, $bgColor 100%);
        background-clip: text;
        -webkit-background-clip: text;
        color: transparent;
        -webkit-text-stroke: 2px $bgColor;
        filter: drop-shadow(0 0 5px $secondaryColor);
    }

    .imageWrapper {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;

        img {
            width: 65%;
            filter: drop-shadow(0 0 5px $primaryColor);
        }
    }

    @keyframes moveHeader {
        0% {
            transform: scale(1.4) translateY(0);
        }

        50% {
            transform: scale(1) translateY(0);
        }

        100% {
            transform: scale(1) translateY(-15vh);
        }
    }
}

.logoMinimized {
    display: flex;
    transform: scale(.9);
    animation: none;

    h1 {
        text-align: center;
        font-size: 3vw;
    }
}
</style>

// battle-towers-react/src/components/BattleTowers.tsx
import { useEffect, useState, useContext } from 'react';
import { animated, useSpring } from 'react-spring';
import shield from './../assets/img/shield.png';
import { AppContext, AppContextType } from './AppContext';
import Intro from './views/Intro';
import Menu from './views/Menu';
import Game from './views/Game';
import styles from './../assets/scss/modules/Logo.module.scss';
import End from './views/End';
import { GameResult } from '../enums';
import useSound from 'use-sound';


const BattleTowers = () => {
  const [changeState, setChangeState] = useState<boolean>(false);
  const { isGameStart, endGame, playMenu } = useContext(AppContext) as AppContextType;

  const stateAnimation = useSpring({
    from: {
      opacity: 0
    },
    to: {
      opacity: 1
    }
  });

  useEffect(() => {
    playMenu();
  }, []);

  return (
    <animated.div className="wrapper" style={stateAnimation}>
      <div className="game">
        {!isGameStart ?
          <>
            <header className={styles.logo}>
              <div className={styles.imageWrapper}>
                <img src={shield} alt="Shield - element of Battle Towers logo" />
              </div>
              <h1>Battle Towers</h1>
            </header>
            {!changeState ? <Intro setChangeState={setChangeState} /> : <Menu />}
          </> :
          <>{endGame === GameResult.UNPLAYED && <Game />}</>
        }
        {/* <Game /> */}
        {endGame !== GameResult.UNPLAYED && <End gameResult={endGame} />}
      </div>

    </animated.div>
  );
}

export default BattleTowers;
