// battle-towers-vue/src/components/features/battleJournal/EnemyCard.vue
<template>
    <div class="card">
        <h3>{{ name }} Orc</h3>
        <div class="imgWrapper">
            <img :src="img" :alt="`${name} Orc`" />
        </div>
        <p class="health">Health: {{ health }}</p>
        <p class="money">Money: {{ money }}</p>
        <p class="speed">Speed: {{ speed }} FPS</p>
        <p class="score">Score: {{ score }}</p>
        <p class="opponent">
            <span>Best tower</span>
            <span>{{ opponent }}</span>
        </p>
    </div>
</template>
<script lang="ts">


export default {
    name: 'EnemyCard',
    props: {
        name: {
            type: String,
            required: true
        },
        img: {
            type: String,
            required: true
        },
        health: {
            type: Number,
            required: true
        },
        money: {
            type: Number,
            required: true
        },
        speed: {
            type: Number,
            required: true
        },
        score: {
            type: Number,
            required: true
        },
        opponent: {
            type: String,
            required: true
        }
    }
};
</script>
<style lang="scss" scoped>
@import '@/assets/scss/variables';

.cards {
    display: flex;
    justify-content: space-evenly;
    align-items: center;

    .card {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        border: 2px solid $primaryColor;
        width: 30%;
        padding: 20px;
        color: $fontColor;
        line-height: 250%;
        font-size: 1.5rem;
        border-radius: 4px;
        background-color: darken($bgColor, 4%);

        .imgWrapper {
            height: 15vh;
            margin: 1rem;

            img {
                width: 100%;
                height: 100%;
            }
        }

        .health {
            color: $errorColor;
        }

        .money {
            color: $successColor;
        }

        .score {
            color: $primaryColor;
        }

        .speed {
            color: gold;
        }

        .opponent {
            span {
                display: block;
            }

            color: rebeccapurple;
            text-align: center;
        }
    }
}
</style>

// battle-towers-react/src/components/features/battleJournal/EnemyCard.tsx
import styles from './../../../assets/scss/modules/BattleJournal.module.scss';
interface EnemyCardProps {
  name: string
  img: string,
  health: number,
  money: number,
  speed: number,
  score: number,
  opponent: string,
}
const EnemyCard = ({ name, img, health, money, speed, score, opponent }: EnemyCardProps) => {
  return (
    <div className={styles.card}>
      <h3>{name} Orc</h3>
      <div className={styles.imgWrapper}>
        <img src={img} alt={`${name} Orc`} />
      </div>
      <p className={styles.health}>Health: {health}</p>
      <p className={styles.money}>Money: {money}</p>
      <p className={styles.speed}>Speed: {speed} FPS</p>
      <p className={styles.score}>Score: {score}</p>
      <p className={styles.opponent}>
        <span>Best tower</span>
        <span>{opponent}</span>
      </p>
    </div>
  );
}

export default EnemyCard;
