// battle-towers-vue/src/components/Playground.vue
<script lang="ts">
import { ref, watch, reactive, computed, onMounted } from 'vue';
// import { useRoute } from 'vue-router';
// import { useStore } from 'vuex';
// import { useSound } from 'vue-use-sound';


import Enemy from '@/classes/enemies/Enemy';
import Tower from '@/classes/towers/Tower';
import Substructure from '@/classes/Substructure';
import Scene from '@/classes/Scene';
import Player from '@/classes/Player';
import Explosion from '@/classes/Explosion';

import fillSubstructures from '@/scripts/fillSubstructures';
import spawnEnemies from '@/scripts/spawnEnemies';
import addToLogs from '@/scripts/addToLogs';
import mouseMove from '@/scripts/mouseMove';

import TransitionInfo from '@/components/features/TransitionInfo.vue';
import NewTowerMenu from '@/components/features/towerMenu/NewTowerMenu.vue';
// import UpgradeTowerMenu from '@/components/features/towerMenu/UpgradeTowerMenu.vue';

// import Loading from '@/components/views/Loading';

import { useGameStore } from '@/stores/game';
import { useAppStore } from '@/stores/app';

import lostLife from './../assets/audio/effects/lostLife.wav';
import enemyDead from './../assets/audio/effects/enemyDead.wav';
import enemyHit from './../assets/audio/effects/enemyHit.wav';
import nextGamePart from './../assets/audio/effects/nextGamePart.wav';

import desertSoundtrack from './../assets/audio/tracks/world1Soundtrack.mp3';
import forestSoundtrack from './../assets/audio/tracks/world2Soundtrack.mp3';
import underworldSoundtrack from './../assets/audio/tracks/world3Soundtrack.wav';
import { CanvasBounding, GamePart, GameResult, LogType } from '@/typescript/enums';
import type { Mouse } from '@/typescript/types';

export default {
    components: {
        TransitionInfo,
        // NewTowerMenu,
        // UpdateTowerMenu,
    },
    setup() {
        const gameStore = useGameStore();
        const appStore = useAppStore();
        const { setWave, setLevel, setWorld, setLife, setMoney, setScore, logs, setLogs } = gameStore;
        const { setEndGame } = appStore;

        const lostLifeEffect = new Audio(lostLife);
        const enemyDeadEffect = new Audio(enemyDead);
        const enemyHitEffect = new Audio(enemyHit);
        const nextGamePartEffect = new Audio(nextGamePart);

        const desertTrack = new Audio(desertSoundtrack);
        const forestTrack = new Audio(forestSoundtrack);
        const underworldTrack = new Audio(underworldSoundtrack);

        const canvasRef = ref<HTMLCanvasElement | null>(null);
        const context2D = ref<CanvasRenderingContext2D | null>(null);

        const animationRef = ref(0);
        const isLoaded = ref(false);
        const initCanvas = ref(false);
        const isInitialized = ref(false);

        const info = ref('');
        const time = ref(3);
        const isInfoVisible = ref(false);

        const contextMenuPosition = ref({ x: -1000, y: 0 });
        const contextMenu = ref(null);
        const clickedTower = ref(null);
        const mousePosition = ref({ x: 0, y: 0 });
        const tacticalMode = ref(false);

        const towers = ref<Tower[]>([]);
        const enemies = ref<Enemy[]>([]);
        const explosions = ref<Explosion[]>([]);
        const substructures = ref<Substructure[]>([]);

        const currentSubstructure = ref(null);

        const player = ref<Player | null>(null);
        const scene = ref<Scene | null>(null);

        const gamePart = ref<GamePart | null>(null);
        const start = ref(false);

        let activeSubstructure = ref(null);

        const initialize = () => {
            if (canvasRef.value) {
                canvasRef.value.width = CanvasBounding.WIDTH;
                canvasRef.value.height = CanvasBounding.HEIGHT;
                context2D.value!.fillRect(0, 0, canvasRef.value.width, canvasRef.value.height);
                setLife(player.value!.getLife());
                setMoney(player.value!.getMoney());
                setScore(player.value!.getScore());
                setWave(scene.value!.getWave());
                setLevel(scene.value!.getLevel());
                setWorld(scene.value!.getWorldName());
                substructures.value = fillSubstructures(context2D.value!, scene.value!);
                enemies.value = spawnEnemies(context2D.value!, scene.value! as Scene);
                explosions.value = [];
                isInitialized.value = true;
            }
        }
        const animate = () => {
            animationRef.value = requestAnimationFrame(animate);
            const image = new Image();
            image.src = scene.value!.getCurrentMap();
            context2D.value!.drawImage(image, 0, 0);
            // updateTowers();
            updateEnemies();
            updateSubstructures({ x: 0, y: 0 });
            // updateExplosions();
        }
        const refreshAssets = () => {

        }

        const updateEnemies = () => {
            for (let i = enemies.value.length - 1; i >= 0; i--) {
                const enemy = enemies.value[i];
                // console.log(enemy);
                enemy.update();
                // console.log(typeof enemy);
                decreasePlayerLife(enemy as Enemy, i);
            }
        }

        const updateSubstructures = (mouse: Mouse) => {
            substructures.value.forEach(substructure => substructure.update(mouse));
        }

        const decreasePlayerLife = (enemy: Enemy, index: number) => {
            const worldData = scene.value!.getCurrentWorldData();
            if (enemy.getWaypointIndex() === worldData.waypoints.length - 1) {
                player.value!.setLife(player.value!.getLife() - 1);
                addToLogs(logs, 'Lost life!', LogType.FAILURE);
                setLife(player.value!.getLife());
                enemies.value.splice(index, 1);
                lostLifeEffect.play();
                if (player.value!.getLife() <= 0) {
                    setEndGame(GameResult.DEFEAT);
                    gameReset();
                }
                if (enemies.value.length === 0) increaseWave();
            }
        }
        const gameReset = () => {
            desertTrack.pause();
            forestTrack.pause();
            underworldTrack.pause();
            cancelAnimationFrame(animationRef.value);
            scene.value!.setWave(1);
            scene.value!.setLevel(1);
            scene.value!.setWorld(1);
            setWave(1);
            setLevel(1);
            setWorld(scene.value!.getWorldName());
            logs.slice(0, logs.length);
            setLogs([]);
        }
        const increaseWave = () => {
            if (scene.value!.getWave() >= scene.value!.getCurrentWorldData().enemies.length) increaseLevel();
            else {
                gamePart.value = GamePart.WAVE;
                scene.value!.setWave(scene.value!.getWave() + 1);
                enemies.value = spawnEnemies(context2D.value!, scene.value! as Scene);
            }
        }
        const increaseLevel = () => {

        }
        const changeWorld = () => {

        }
        const gameTransition = (part: GamePart) => {
            setTimeout(() => {
                isLoaded.value = true;
            }, 2000);
            nextGamePartEffect.play();
            isInfoVisible.value = true;
            info.value = part;

            if (part === GamePart.START && start) {
                if (scene.value!.getWorldName() === 'Desert') desertTrack.play();
                if (scene.value!.getWorldName() === 'Forest') forestTrack.play();
                if (scene.value!.getWorldName() === 'Underworld') underworldTrack.play();
                isInfoVisible.value = false;
                animate();
            } else if ((part === GamePart.WAVE || part === GamePart.LEVEL) && start) {
                if (player.value!.getLife() <= 0) return;
                setTimeout(() => {
                    isInfoVisible.value = false;
                    animate();
                    if (part === GamePart.WAVE) {
                        setWave(scene.value!.getWave());
                        addToLogs(logs, 'Next Wave!', LogType.SUCCESS);
                    } else if (part === GamePart.LEVEL) {
                        setMoney(player.value!.getMoney());
                        setLevel(scene.value!.getLevel());
                        setWave(1);
                        addToLogs(logs, 'Next Level!', LogType.SUCCESS);
                    }
                }, 4000);

                let index = 3;
                const interval = setInterval(() => {
                    if (index === 0) {
                        clearInterval(interval);
                        time.value = 3;
                    } else {
                        index--;
                        time.value = index;
                    }
                }, 1000);
            } else if (part === GamePart.WORLD) {
                desertTrack.pause();
                forestTrack.pause();
                underworldTrack.pause();
                if (scene.value!.getWorldName() === 'Desert') desertTrack.play();
                if (scene.value!.getWorldName() === 'Forest') forestTrack.play();
                if (scene.value!.getWorldName() === 'Underworld') underworldTrack.play();
                setWave(1);
                setLevel(1);
                setWorld(scene.value!.getWorldName());
                setLife(player.value!.getLife());
                setMoney(player.value!.getMoney());
                addToLogs(logs, 'Next World!', LogType.SUCCESS);
                cancelAnimationFrame(animationRef.value);
            }
            gamePart.value = null;
        }




        const handleTacticalMode = () => {
            console.log('click');
        }

        onMounted(() => {
            const canvas = canvasRef.value;
            const ctx = canvas?.getContext('2d');
            if (!ctx) return;
            context2D.value = ctx;
            initCanvas.value = true;
        });
        watch(
            () => initCanvas.value,
            (newInitCanvas) => {
                scene.value = new Scene();
                player.value = new Player();
                if (newInitCanvas) initialize();
            }
        );
        watch(
            () => isInitialized.value,
            (newIsInitialized) => {
                if (newIsInitialized) {
                    const image = new Image();
                    image.src = scene.value!.getCurrentMap();
                    image.onload = () => { gameTransition(GamePart.START); };
                }
            }
        );
        watch(
            () => start.value,
            (newStart) => {
                if (isInitialized.value) {
                    if (newStart) gameTransition(GamePart.START);
                    else gameTransition(GamePart.WORLD);
                }
            }
        );
        watch(
            [initCanvas, gamePart],
            ([newInitCanvas, newGamePart]) => {
                if (newInitCanvas && newGamePart) {
                    cancelAnimationFrame(animationRef.value);
                    gameTransition(newGamePart);
                }
            }
        );
        watch(
            () => towers.value.length,
            () => {
                if (isInitialized.value && tacticalMode.value) {
                    refreshAssets();
                }
            }
        );
        return {
            isLoaded,
            setWave,
            setLevel,
            setWorld,
            setLife,
            setMoney,
            setScore,
            setEndGame,
            logs,
            setLogs,
            canvasRef,
            animationRef,
            context2D,
            initCanvas,
            isInitialized,
            info,
            time,
            isInfoVisible,
            contextMenuPosition,
            contextMenu,
            clickedTower,
            mousePosition,
            tacticalMode,
            towers,
            enemies,
            explosions,
            substructures,
            currentSubstructure,
            scene,
            player,
            gamePart,
            start,
            activeSubstructure,
            handleTacticalMode,
        };
    },
};
</script>
<template>
    <div class="canvasWrapper">
        <div class="tacticalModeBtn">
            <i @click="handleTacticalMode" class="fa fa-pause-circle-o" aria-hidden="true"></i>
        </div>
        <div class="fade">
            <span v-if="tacticalMode" class="tacticalMode">Tactical Mode is Active</span>
            <TransitionInfo v-if="isInfoVisible" :info="info" :time="time" :start="start" />
            <!-- <NewTowerMenu v-if="contextMenu === ContextMenu.NEW_TOWER" :contextMenuPosition="contextMenuPosition"
                                                                                                                                                                                                    :currentSubstructure="currentSubstructure" :setCurrentSubstructure="setCurrentSubstructure"
                                                                                                                                                                                                    :setContextMenu="setContextMenu" :context2D="context2D" :towers="towers" :player="player" />
                                                                                                                                                                                                <UpgradeTowerMenu v-if="contextMenu === ContextMenu.UPGRADE_TOWER" :contextMenuPosition="contextMenuPosition"
                                                                                                                                                                                                    :setContextMenu="setContextMenu" :currentSubstructure="currentSubstructure" :towers="towers"
                                                                                                                                                                                                    :currentTower="clickedTower" :player="player" :refreshAssets="refreshAssets" /> -->

            <canvas ref="canvasRef" class="sceneCanvas"></canvas>

            <!-- <canvas ref="canvasRef" class="sceneCanvas" @click="placementClicked"
                                                                                                                                                                                                    @mousemove="event => mouseMove({ event, canvasRef, tacticalMode, setMousePosition, updateSubstructures })"></canvas> -->
        </div>
        <Loading v-if="!isLoaded" />
    </div>
</template>
<style lang="scss">
@import '../assets/scss/_variables.scss';

.fade {
    opacity: 0;
    animation: fadeIn .4s ease-out forwards;

    @keyframes fadeIn {
        from {
            opacity: 0;
        }

        to {
            opacity: 1;
        }
    }
}

.canvasWrapper {
    position: relative;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;

    .tacticalModeBtn {
        position: absolute;
        right: 2rem;
        bottom: 1rem;
        font-size: 6rem;
        color: $secondaryColor;
        text-shadow: 1px 1px 5px black,
            -1px 1px 5px black,
            1px -1px 5px black,
            -1px -1px 5px black;
        filter: drop-shadow(0 0 0.75rem black);
        animation-delay: 3000ms;
        animation-name: myAnimation;
        animation-duration: 1s;
        animation-fill-mode: forwards;
        transform: scale(0);
        z-index: 100;

        i {
            transition-duration: .4s;

            &:hover {
                cursor: pointer;
                color: $primaryColor;
            }
        }

        @keyframes myAnimation {
            0% {
                transform: scale(0);
            }

            100% {
                transform: scale(1);
            }
        }
    }

    .tacticalMode {
        position: absolute;
        top: 0;
        left: 0;
        margin: 1rem;
        color: $primaryColor;
        font-size: 2rem;
        background-color: $bgColor;
        padding: 1rem;
        opacity: .7;
        border-radius: 4px;
    }

    .transitionInfo {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        text-align: center;
        color: $fontColor;
        font-family: $titleFont;
        font-size: 8rem;
        background-color: #000;
        opacity: .8;
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 5px;
        z-index: 3;

        h3 {
            width: 100%;
            padding: 20%;
            -webkit-text-stroke: 1px $secondaryColor;
        }
    }

    .newTowerMenu {
        position: absolute;
        border-radius: 8px;
        border: 2px solid $secondaryColor;
        background-color: #202022c3;
        padding: 20px;
        width: 450px;
        height: 440px;

        h2 {
            text-align: center;
            font-size: 2.5rem;
            color: $primaryColor;
            font-family: $primaryFont;
            margin-bottom: 1rem;
            filter: drop-shadow(0 0 0.75rem black);
        }

        .newTower {
            position: relative;
            display: flex;
            align-items: center;
            justify-content: space-evenly;
            transition-duration: .4s;
            border-radius: 4px;
            margin: 1rem;

            .error {
                position: absolute;
                display: flex;
                justify-content: center;
                align-items: center;
                z-index: 10;
                background-color: rgba(0, 0, 0, 0.5);
                color: red;
                width: 100%;
                height: 100%;
                font-size: 2rem;
                font-family: $primaryFont;
                border-radius: 4px;
            }

            &:hover {
                cursor: pointer;
                background-color: $primaryColor;
            }

            .imageWrapper {
                width: 80%;
                margin: 20px;
                color: $fontColor;

                p {
                    filter: drop-shadow(0 0 0.75rem black);
                    margin-bottom: 2rem;
                }

                img {
                    width: 50%;
                    height: 50%;
                }
            }

            .infoWrapper {
                display: flex;
                justify-content: center;
                align-items: center;
                flex-direction: column;
                width: 100%;
                line-height: 150%;
                font-size: 1.2rem;

                .health {
                    color: $errorColor;
                    filter: drop-shadow(0 0 0.75rem black);
                }

                .money {
                    color: $successColor;
                    filter: drop-shadow(0 0 0.75rem black);
                }

                .speed {
                    color: gold;
                    filter: drop-shadow(0 0 0.75rem black);
                }
            }
        }
    }

    .upgradeTowerMenu {
        position: absolute;
        border-radius: 8px;
        border: 2px solid $secondaryColor;
        background-color: #202022c3;
        padding: 20px;
        width: 470px;
        height: 550px;

        h2 {
            text-align: center;
            font-size: 2.5rem;
            margin-bottom: 1rem;
            color: $primaryColor;
            font-family: $primaryFont;
            filter: drop-shadow(0 0 0.75rem black);
        }

        i {
            display: block;
            color: $secondaryColor;
            font-size: 10rem;
            text-align: center;
        }


        button {
            display: block;
            text-align: center;
            margin: 0 auto;
            margin-top: 2rem;
            width: 80%;
            height: 5vh;
            border-radius: 4px;
            outline: none;
            border: 2px solid $secondaryColor;
            background-color: $primaryColor;
            color: darken($secondaryColor, 10%);
            font-size: 2rem;
            font-weight: bold;
            font-family: $supportFont;
            transition-duration: .4s;
            outline: 2px solid $secondaryColor;

            &.error {
                color: $errorColor;
                font-size: 1.5rem;
                outline: 2px solid $errorColor;
                border: 2px solid $errorColor;
                background-color: darken($errorColor, 30%);
                color: $errorColor;

                &:hover {
                    border-color: $errorColor;
                    background-color: lighten($errorColor, 20%);
                    color: $bgColor;
                    outline-color: $errorColor;
                }
            }

            &:hover {
                cursor: pointer;
                border-color: $primaryColor;
                background-color: $secondaryColor;
                color: $primaryColor;
                outline-offset: 4px;
                outline-color: $primaryColor;
            }
        }

        .upgradeTower {
            display: flex;
            align-items: center;
            justify-content: space-evenly;
            transition-duration: .4s;
            border-radius: 4px;
            border: 2px solid $secondaryColor;
            background-color: #00747c4e;

            .imageWrapper {
                width: 80%;
                margin: 20px;
                color: $fontColor;

                p {
                    filter: drop-shadow(0 0 0.75rem black);
                    margin-bottom: 2rem;
                }

                img {
                    width: 50%;
                    height: 50%;
                }
            }

            .infoWrapper {
                display: flex;
                justify-content: center;
                align-items: center;
                flex-direction: column;
                width: 100%;
                line-height: 150%;
                font-size: 1.2rem;

                .health {
                    color: $errorColor;
                    filter: drop-shadow(0 0 0.75rem black);
                }

                .money {
                    color: $successColor;
                    filter: drop-shadow(0 0 0.75rem black);
                }

                .speed {
                    color: gold;
                    filter: drop-shadow(0 0 0.75rem black);
                }
            }
        }
    }

    .maxLevel {
        position: absolute;
        border-radius: 8px;
        border: 2px solid $secondaryColor;
        background-color: #202022c3;
        padding: 20px;
        width: 470px;
        height: 250px;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        text-align: center;

        h2 {

            padding: 2rem 0;

            &:first-child {
                color: $primaryColor;
                font-size: 2rem;
            }

            &:last-child {
                color: $fontColor;
                font-size: 1.7rem;
                filter: drop-shadow(0 0 0.75rem black);
            }
        }

        img {
            width: 30%;
        }
    }

    .sceneCanvas {
        width: $canvasWidth;
        height: $canvasHeight;
        background-color: green;
        border-radius: 5px;
        border: 2px solid $secondaryColor;
        box-shadow: 0 0 4px 2px $secondaryColor;
        z-index: 1;
    }
}
</style>

// battle-towers-next/src/components/Playground.tsx
import { useEffect, useContext, useState, useRef } from 'react';
import { AppContext, AppContextType } from './AppContext';
import useSound from 'use-sound';

import styles from './../assets/scss/modules/Playground.module.scss';

// import lostLife from './../assets/audio/effects/lostLife.wav';
// import enemyDead from './../assets/audio/effects/enemyDead.wav';
// import enemyHit from './../assets/audio/effects/enemyHit.wav';
// import nextGamePart from './../assets/audio/effects/nextGamePart.wav';

// import desertSoundtrack from './../assets/audio/tracks/world1Soundtrack.mp3';
// import forestSoundtrack from './../assets/audio/tracks/world2Soundtrack.mp3';
// import underworldSoundtrack from './../assets/audio/tracks/world3Soundtrack.wav';
import Loading from './views/Loading';
import { Mouse } from '../../types';
import { CanvasBounding, ContextMenu, GamePart, GameResult, LogType } from '../../enums';
import Tower from '@/classes/towers/Tower';
import Enemy from '@/classes/enemies/Enemy';
import Explosion from '@/classes/Explosion';
import Substructure from '@/classes/Substructure';
import Scene from '@/classes/Scene';
import Player from '@/classes/Player';
import fillSubstructures from '@/scripts/fillSubstructures';
import spawnEnemies from '@/scripts/spawnEnemies';
import addToLogs from '@/scripts/addToLogs';
import mouseMove from '@/scripts/mouseMove';
import { animated, useSpring } from 'react-spring';
import TransitionInfo from './features/TransitionInfo';
import NewTowerMenu from './features/towerMenu/NewTowerMenu';
import UpgradeTowerMenu from './features/towerMenu/UpgradeTowerMenu';

interface PlaygroundProps {
  isLoaded: boolean;
  setIsLoaded: (isLoaded: boolean) => void;
}

const Playground = ({ isLoaded, setIsLoaded }: PlaygroundProps) => {

  // const [playLostLife] = useSound(lostLife);
  // const [playEnemyDead] = useSound(enemyDead);
  // const [playEnemyHit] = useSound(enemyHit);
  // const [playNextGamePart] = useSound(nextGamePart);

  const { setWave, setLevel, setWorld, setLife, setMoney, setScore, setEndGame, logs, setLogs } = useContext(AppContext) as AppContextType;

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const animationRef = useRef<number>(null!);

  const [context2D, setContext2D] = useState<CanvasRenderingContext2D | null>(null);

  const [initCanvas, setInitCanvas] = useState(false);
  const [isInitialized, setIsInitialized] = useState(false);

  const [info, setInfo] = useState('');
  const [time, setTime] = useState(3);
  const [isInfoVisible, setIsInfoVisible] = useState(false);

  const [contextMenuPosition, setContextMenuPosition] = useState<Mouse>({ x: -1000, y: 0 });
  const [contextMenu, setContextMenu] = useState<ContextMenu | null>(null);
  const [clickedTower, setClickedTower] = useState<Tower | null>(null);
  const [mousePosition, setMousePosition] = useState<Mouse>({ x: 0, y: 0 });
  const [tacticalMode, setTacticalMode] = useState(false);

  const [towers, setTowers] = useState<Tower[]>([]);
  const [enemies, setEnemies] = useState<Enemy[]>([]);
  const [explosions, setExplosions] = useState<Explosion[]>([]);

  const [substructures, setSubstructures] = useState<Substructure[]>([]);
  const [currentSubstructure, setCurrentSubstructure] = useState<Substructure | null>(null);

  const [scene, setScene] = useState<Scene | null>(null);
  const [player, setPlayer] = useState<Player | null>(null);

  const [gamePart, setGamePart] = useState<GamePart | null>(null);
  const [start, setStart] = useState(false);

  // const [playDesert, { stop: stopDesert }] = useSound(desertSoundtrack, {
  //   volume: 0.5,
  //   interrupt: true,
  //   loop: true,
  // });
  // const [playForest, { stop: stopForest }] = useSound(forestSoundtrack, {
  //   volume: 0.5,
  //   interrupt: true,
  //   loop: true,
  // });
  // const [playUnderworld, { stop: stopUnderworld }] = useSound(underworldSoundtrack, {
  //   volume: 0.5,
  //   interrupt: true,
  //   loop: true,
  // });

  const stateAnimation = useSpring({
    opacity: isLoaded ? 1 : 0,
    config: { duration: 400 },
    delay: 200
  });

  let activeSubstructure: Substructure | null = null;

  const initialize = () => {
    canvasRef.current!.width = CanvasBounding.WIDTH;
    canvasRef.current!.height = CanvasBounding.HEIGHT;
    context2D!.fillRect(0, 0, canvasRef.current!.width, canvasRef.current!.height);
    setLife(player!.getLife());
    setMoney(player!.getMoney());
    setScore(player!.getScore());
    setWave(scene!.getWave());
    setLevel(scene!.getLevel());
    setWorld(scene!.getWorldName());
    setSubstructures(fillSubstructures(context2D!, scene!));
    setEnemies(spawnEnemies(context2D!, scene!));
    setExplosions([]);
    setIsInitialized(true);
    const image = new Image();
    image.src = scene!.getCurrentMap();
    context2D!.drawImage(image, 0, 0);
  }

  const checkSubstructure = (activeSubstructure: Substructure) => {
    setCurrentSubstructure(activeSubstructure);
    if (!activeSubstructure.getOccupied()) setContextMenu(ContextMenu.NEW_TOWER);
    else {
      const tower = towers.filter((tower) => tower.getPosition().x === activeSubstructure.getPosition().x && tower.getPosition().y === activeSubstructure.getPosition().y);
      setClickedTower(tower[0]);
      setContextMenu(ContextMenu.UPGRADE_TOWER);
    }
  }

  const placementClicked = () => {
    for (let i = 0; i < substructures.length; i++) {
      const tile = substructures[i];
      if (
        mousePosition.x > tile.getPosition().x &&
        mousePosition.x < tile.getPosition().x + tile.getSize() &&
        mousePosition.y > tile.getPosition().y &&
        mousePosition.y < tile.getPosition().y + tile.getSize()
      ) {
        activeSubstructure = tile;
        break;
      }
    }
    if (activeSubstructure) {
      setContextMenuPosition({ x: mousePosition.x, y: mousePosition.y });
      checkSubstructure(activeSubstructure);
    } else {
      setContextMenuPosition({ x: -1000, y: 0 });
      setContextMenu(ContextMenu.NONE);
    }
  }

  const animate = () => {
    animationRef.current = requestAnimationFrame(animate);
    const image = new Image();
    image.src = scene!.getCurrentMap();
    context2D!.drawImage(image, 0, 0);
    updateTowers();
    updateEnemies();
    updateSubstructures({ x: 0, y: 0 });
    updateExplosions();
    console.log('animate');
  }

  const refreshAssets = () => {
    const image = new Image();
    image.src = scene!.getCurrentMap();
    context2D!.drawImage(image, 0, 0);
    updateTowers();
    updateEnemies();
    updateSubstructures({ x: 0, y: 0 });
    updateExplosions();
  }

  const updateEnemies = () => {
    for (let i = enemies.length - 1; i >= 0; i--) {
      const enemy = enemies[i];
      enemy.update();
      decreasePlayerLife(enemy, i);
    }
  }

  const updateSubstructures = (mouse: Mouse) => { substructures.forEach(substructure => substructure.update(mouse)); }

  const updateTowers = () => {
    towers.forEach(tower => {
      tower.update();
      tower.setTarget(null);
      const validEnemies = enemies.filter(enemy => {
        const xDifference = (enemy.getPosition().x + enemy.getBounding().width / 2) - tower.getPosition().x - tower.getSize() / 2;
        const yDifference = (enemy.getPosition().y + enemy.getBounding().height / 2) - tower.getPosition().y - tower.getSize() / 2;
        const distance = Math.hypot(xDifference, yDifference);
        return distance < enemy.getBounding().radius + tower.getRadius();
      });
      tower.setTarget(validEnemies[validEnemies.length - 1]);
      updateBullet(tower, enemies);
    });
  }

  const updateBullet = (tower: Tower, enemies: Enemy[]) => {
    for (let i = tower.getBullets().length - 1; i >= 0; i--) {
      const bullet = tower.getBullet(i);
      bullet.update();
      const xDifference = (bullet.getEnemy().getPosition().x + bullet.getEnemy().getBounding().width / 2) - bullet.getPosition().x;
      const yDifference = (bullet.getEnemy().getPosition().y + bullet.getEnemy().getBounding().height / 2) - bullet.getPosition().y;
      const distance = Math.hypot(xDifference, yDifference);
      if (distance < bullet.getEnemy().getBounding().radius) {
        bullet.getEnemy().decreaseHealth(tower.getDamage());
        explosions.push(new Explosion(
          context2D!,
          { x: bullet.getEnemy().getPosition().x, y: bullet.getEnemy().getPosition().y },
          tower.getExplosionImg(),
          { max: tower.getMaxExplosionFrames() })
        );
        tower.getBullets().splice(i, 1);
        // playEnemyHit();
        if (bullet.getEnemy().getHealth() <= 0) {
          const enemyIndex = enemies.findIndex((enemy) => {
            return bullet.getEnemy() === enemy;
          });
          if (enemyIndex > -1) {
            const targetedEnemy = enemies[enemyIndex];
            enemies.splice(enemyIndex, 1);
            // playEnemyDead();
            addToLogs(logs, `${targetedEnemy.getName()} has been eliminated!`, LogType.SUCCESS);
            player!.setMoney(player!.getMoney() + targetedEnemy.getMoney());
            player!.setScore(player!.getScore() + targetedEnemy.getScore());
            setScore(player!.getScore());
            setMoney(player!.getMoney());
          }
        }
        if (enemies.length === 0) increaseWave();
      }
    }
  }
  const updateExplosions = () => {
    for (let i = explosions.length - 1; i >= 0; i--) {
      const explosion = explosions[i];
      explosion.update();
      if (explosion.getFrames().current >= explosion.getFrames().max - 1) explosions.splice(i, 1);
    }
  }

  const gameTransition = (part: GamePart) => {
    setTimeout(() => {
      setIsLoaded(true);
    }, 2000);
    // playNextGamePart();
    setIsInfoVisible(true);
    setInfo(part);
    if (part === GamePart.START && start) {
      // if (scene!.getWorldName() === 'Desert') playDesert();
      // if (scene!.getWorldName() === 'Forest') playForest();
      // if (scene!.getWorldName() === 'Underworld') playUnderworld();
      setIsInfoVisible(false);
      animate();
    } else if ((part === GamePart.WAVE || part === GamePart.LEVEL) && start) {
      if (player!.getLife() <= 0) return;
      setTimeout(() => {
        setIsInfoVisible(false);
        animate();
        if (part === GamePart.WAVE) {
          setWave(scene!.getWave());
          addToLogs(logs, 'Next Wave!', LogType.SUCCESS);
        } else if (part === GamePart.LEVEL) {
          setMoney(player!.getMoney());
          setLevel(scene!.getLevel());
          setWave(1);
          addToLogs(logs, 'Next Level!', LogType.SUCCESS);
        }
      }, 4000);

      let index = 3;
      const interval = setInterval(() => {
        if (index === 0) {
          clearInterval(interval);
          setTime(3);
        } else {
          index--;
          setTime(index);
        }
      }, 1000);
    } else if (part === GamePart.WORLD) {
      // stopDesert();
      // stopForest();
      // stopUnderworld();
      // if (scene!.getWorldName() === 'Desert') playDesert();
      // if (scene!.getWorldName() === 'Forest') playForest();
      // if (scene!.getWorldName() === 'Underworld') playUnderworld();
      setWave(1);
      setLevel(1);
      setWorld(scene!.getWorldName());
      setLife(player!.getLife());
      setMoney(player!.getMoney());
      addToLogs(logs, 'Next World!', LogType.SUCCESS);
      cancelAnimationFrame(animationRef.current);
    }
    setGamePart(null);
  }

  const gameReset = () => {
    // stopDesert();
    // stopForest();
    // stopUnderworld();
    cancelAnimationFrame(animationRef.current);
    scene!.setWave(1);
    scene!.setLevel(1);
    scene!.setWorld(1);
    setWave(1);
    setLevel(1);
    setWorld(scene!.getWorldName());
    logs.slice(0, logs.length);
    setLogs([]);
  }

  const decreasePlayerLife = (enemy: Enemy, index: number) => {
    const worldData = scene!.getCurrentWorldData();
    if (enemy.getWaypointIndex() === worldData.waypoints.length - 1) {
      player!.setLife(player!.getLife() - 1);
      addToLogs(logs, 'Lost life!', LogType.FAILURE);
      setLife(player!.getLife());
      enemies.splice(index, 1);
      // playLostLife();
      if (player!.getLife() <= 0) {
        setEndGame(GameResult.DEFEAT);
        gameReset();
      }
      if (enemies.length === 0) increaseWave();
    }
  }

  const increaseWave = () => {
    if (scene!.getWave() >= scene!.getCurrentWorldData().enemies.length) increaseLevel();
    else {
      setGamePart(GamePart.WAVE);
      scene!.setWave(scene!.getWave() + 1);
      setEnemies(spawnEnemies(context2D!, scene!));
    }
  }

  const increaseLevel = () => {
    if (scene!.getLevel() >= scene!.getMaps().length) changeWorld();
    else {
      setGamePart(GamePart.LEVEL);
      scene!.setLevel(scene!.getLevel() + 1);
      towers.splice(0, towers.length);
      setTowers([]);
      activeSubstructure = null;
      setSubstructures(fillSubstructures(context2D!, scene!))
      scene!.setWave(1);
      setEnemies(spawnEnemies(context2D!, scene!));
      player!.setMoney(((scene!.getWorld() * 100) + ((scene!.getLevel() - 1) * 20)));
      setContextMenu(null);
    }
  }

  const changeWorld = () => {
    if (scene!.getWorld() >= scene!.getWorldsLength()) {
      setEndGame(GameResult.WIN);
      player!.setScore(player!.getScore() + player!.getLife() * 100);
      setScore(player!.getScore());
      gameReset();
    } else {
      scene!.setWave(1);
      scene!.setLevel(1);
      scene!.setWorld(scene!.getWorld() + 1);
      towers.splice(0, towers.length);
      setTowers([]);
      activeSubstructure = null;
      setStart(false);
      setSubstructures(fillSubstructures(context2D!, scene!));
      setEnemies(spawnEnemies(context2D!, scene!));
      player!.setLife(player!.getLife() + 3);
      player!.setMoney(100 * scene!.getWorld());
      setContextMenu(null);
    }
  }

  const handleTacticalMode = () => {
    if (tacticalMode) animate();
    else cancelAnimationFrame(animationRef.current);
    setTacticalMode(!tacticalMode);
    refreshAssets();
  }

  useEffect(() => {
    const canvas = canvasRef.current;
    const ctx = canvas!.getContext('2d');
    setContext2D(ctx);
    setInitCanvas(true);
  }, []);

  useEffect(() => {
    setScene(new Scene());
    setPlayer(new Player());
    if (initCanvas) initialize();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initCanvas]);

  useEffect(() => {
    if (isInitialized) {
      const image = new Image();
      image.src = scene!.getCurrentMap();
      image.onload = () => { gameTransition(GamePart.START); }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isInitialized]);

  useEffect(() => {
    if (isInitialized) {
      if (start) gameTransition(GamePart.START);
      else gameTransition(GamePart.WORLD);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [start]);

  useEffect(() => {
    if (initCanvas && gamePart) {
      cancelAnimationFrame(animationRef.current);
      gameTransition(gamePart);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [gamePart]);

  useEffect(() => {
    if (isInitialized && tacticalMode) refreshAssets();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [towers.length]);

  return (
    <div className={styles.canvasWrapper} >
      <div className={styles.tacticalModeBtn}>
        <i onClick={handleTacticalMode} className="fa fa-pause-circle-o" aria-hidden="true"></i>
      </div>
      <animated.div style={stateAnimation}>
        {tacticalMode && <span className={styles.tacticalMode}>Tactical Mode is Active</span>}
        {isInfoVisible &&
          <TransitionInfo
            info={info}
            time={time}
            start={start}
            setStart={setStart}
          />
        }
        {contextMenu === ContextMenu.NEW_TOWER &&
          <NewTowerMenu
            contextMenuPosition={contextMenuPosition}
            currentSubstructure={currentSubstructure}
            setCurrentSubstructure={setCurrentSubstructure}
            setContextMenu={setContextMenu}
            context2D={context2D}
            towers={towers}
            player={player!}
          />
        }
        {contextMenu === ContextMenu.UPGRADE_TOWER &&
          <UpgradeTowerMenu
            contextMenuPosition={contextMenuPosition}
            setContextMenu={setContextMenu}
            currentSubstructure={currentSubstructure}
            towers={towers}
            currentTower={clickedTower}
            player={player!}
            refreshAssets={refreshAssets}
          />
        }
        <canvas ref={canvasRef} className={styles.sceneCanvas} onClick={placementClicked} onMouseMove={(event) => mouseMove({ event, canvasRef, tacticalMode, setMousePosition, updateSubstructures })} ></canvas>
      </animated.div>
      {!isLoaded && <Loading />}
    </div >
  );
}

export default Playground;
